services:
  frontend:
    build:
      context: .
      target: base
    environment:
      - REACT_APP_API_BASE_URL=https://bis.proxy.mrkvon.org/https://dev.bis.brontosaurus.cz/api/
      - REACT_APP_CORS_PROXY=https://bis.proxy.mrkvon.org/
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    ports:
      - 3000:3000
    command: docker-entrypoint.sh dev
