on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      target_repo:
        required: true
        type: string
      target_branch:
        required: false
        type: string
        default: 'gh-pages'

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: echo vars
        run: echo "api ${{ vars.API }} ${{ secrets.SENTRY_DSN }} ${{inputs.target_branch}}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: source

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: source/yarn.lock

      - name: Install NPM packages
        run: cd source && yarn install --frozen-lockfile

      - name: Build project
        run: cd source && yarn build
        env:
          PUBLIC_URL: https://${{ vars.URL }}
          REACT_APP_API_BASE_URL: ${{ vars.API }}
          REACT_APP_CORS_PROXY: ${{ vars.CORS_PROXY }}
          REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Checkout dev target
        uses: 'actions/checkout@v3'
        with:
          repository: ${{ inputs.target_repo }}
          ref: ${{ inputs.target_branch }}
          ssh-key: ${{ secrets.DEPLOY_GH_PAGES_SSH_KEY }}
          path: target
          persist-credentials: true

      - name: Push files to target
        run: |
          # move files from source to target repository
          rm -rf target/static/
          cp -r source/build/* target
          cd target
          # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo ${{ vars.URL }} > CNAME
          echo "# Build of bis-frontend (${{ inputs.environment }})

          This is a ${{ inputs.environment }} build of [hnuti-brontosaurus/bis-frontend](https://github.com/hnuti-brontosaurus/bis-frontend) for github pages

          It's generated automatically by github actions. Don't change it directly!" > README.md
          git add .
          git commit --allow-empty -m $GITHUB_SHA
          git push -f
